version: '3'

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
  
  # app1
  app1:
    image: node:current-alpine
    working_dir: /usr/src/app
    volumes:
      - ./services/app:/usr/src/app
    tty: true
    command: [sh, -c, npm run dev]
  # app2
  app2:
    image: node:current-alpine
    working_dir: /usr/src/app
    volumes:
      - ./services/app:/usr/src/app
    tty: true
    command: [sh, -c, npm run dev]

  # rabbitmq
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./services/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password